services:

    
  postgres:
    image: postgres
    container_name: postgresdb
    environment:
      POSTGRES_DB: pressingdb
      POSTGRES_USER: root
      POSTGRES_HOST_AUTH_METHOD: trust
      # POSTGRES_PASSWORD: ""
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

  pressing_api:
    container_name: pressing_api
    build: .
    develop:
      watch: 
      - path: ./src
        action: sync+restart
        target: /app/src
      # - path: ./Pipfile
      #   action: rebuild
    environment:
      database_host: postgresdb
      database_user: root
      database_password: ""
    ports:
      - 8000:8000
    depends_on:
      - postgres
    volumes:
      - ./Pipfile:/app/Pipfile
      - ./Pipfile.lock:/app/Pipfile.lock


volumes:
  db:
    name: pressingdb