services:

    
  postgres:
    image: postgres
    container_name: postgresdb
    environment:
      POSTGRES_DB: pressingdb
      POSTGRES_USER: pressing-api
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

  pressing_api:
    container_name: pressing_api
    build: .
    develop:
      watch: 
      - path: .
        action: sync+restart
        target: /app
      - path: Pipfile
        action: rebuild
    environment:
      database_host: postgresdb
    ports:
      - 8000:8000
    depends_on:
      - postgres


volumes:
  db: