services:
  postgres:
    image: postgres
    container_name: postgresdb
    environment:
      POSTGRES_DB:  ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
        - ./postgres_password.txt:/run/secrets/postgres_password:ro
    volumes:
      - db:/var/lib/postgresql/data

  pressing_api:
    container_name: pressing_api
    image: ghcr.io/merylahounou97/pressing_api:dev
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      - postgres
    volumes:
     - .env:/app/.env:ro

  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok
    ports:
      - "4040:4040"
    environment:
      - NGROK_PORT=8000
      - NGROK_AUTHTOKEN= ${NGROK_AUTHTOKEN} 
    command:  http pressing_api:8000

volumes:
  db:
    name: pressingdb
  pgadmin-data:
    name: pgadmin-data