services:
  postgres:
    image: postgres
    container_name: postgresdb
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
      - ./scripts/init_test_databases.sh:/docker-entrypoint-initdb.d/init_test_databases.sh

  pressing_api:
    container_name: pressing_api
    image: ghcr.io/merylahounou97/pressing_api:dev
    ports:
      - 8000:8000
    depends_on:
      - postgres

  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok
    ports:
      - "4040:4040"
    environment:
      - NGROK_PORT=8000
      - NGROK_AUTHTOKEN= ${NGROK_AUTHTOKEN} 
    command:  http pressing_api:8000

volumes:
  db:
    name: pressingdb
  pgadmin-data:
    name: pgadmin-data