services:
  postgres:
    image: postgres
    container_name: postgresdb
    environment:
      POSTGRES_DB:  ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    volumes:
      - db:/var/lib/postgresql/data
      - ./postgres_password.txt:/run/secrets/postgres_password:ro


  pressing_api:
    container_name: pressing_api
    image: ghcr.io/merylahounou97/pressing_api:dev
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portefolio.rule=Host(`portefolio.ulrichaiounou.com`)"
      - "traefik.http.routers.portefolio.entrypoints=websecure"
      - "traefik.http.routers.portefolio.tls.certresolver=myresolver"
      - "traefik.http.routers.portefolio.middlewares=security-chain"
      - traefik.http.services.portefolio.loadbalancer.server.port=8000
    depends_on:
      - postgres
    volumes:
     - .env:/app/.env:ro
    networks:
      - traefik_net

  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok
    ports:
      - "4040:4040"
    environment:
      - NGROK_PORT=8000
      - NGROK_AUTHTOKEN= ${NGROK_AUTHTOKEN} 
    command:  http pressing_api:80

volumes:
  db:
    name: pressingdb
  pgadmin-data:
    name: pgadmin-data
networks:
  traefik_net:
    external: true