name: check_code_quality
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  check_code_quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black isort Pylint
      - name: Run isort
        run: |
          isort --check .
      - name: Run black
        run: |
          black --check .

      - name: Run Pylint
        run: |
          pylint . || exit 0
          PYLINT_SCORE=$(pylint --fail-under=7 . | grep -oP "(?<=rated at ).*(?=/10)")
          if [ $(echo "$PYLINT_SCORE > 7" | bc) -eq 1 ]; then
            echo "Pylint score is greater than 7: $PYLINT_SCORE"
            exit 0
          else
            echo "Pylint score is not greater than 7: $PYLINT_SCORE"
            exit 1
          fi
